### PR TITLE
General tidy up

### PR DESCRIPTION
**Pull request by ihurst**
Remove some duplicate code for parsing aired date time
Use re.search() instead of re.findall() where possible

### CODE REVIEW

**Comment by CaptainTK** [comment]
Thanks.

**Comment by ihurst** [comment]
Are you ok with this clean-up? I'm still tempted to have a go at breaking the code into separate files, currently going to provide an example with the BBCiD code. But then would like to pull out subtitles and some others. Just think it will mean a lot less people working on same files, and hopefully make it easier for you to manage merges etc :)

**Comment by primaeval** [comment]
I had to duplicate and modify a few functions for my cache branch so I would be grateful for a bit of file seperation.

**Comment by ihurst** [comment]
My current Master branch shows what I'm trying, but please be warned this is still being tested etc :) 

I'm not sure if using Classes is over kill? But just experimenting at the moment.

**Pull request merged**
