### PR TITLE
BBCiD integration continue watching

### LINKED ISSUE #349: Watched status not syncing
The addon updates and maintains the locally stored watched status of shows but it does not sync the status back to the BBC site. 
This is incredibly frustrating because it stops the "Watching" (next episode) list from working properly. 
To be able to use the watching list (arguably one of iPlayer's best features), you have to open iPlayer in a web browser (or official BBC android app) and manually trick the site into thinking you've watched the episode by playing the first 30 seconds and then skipping forward to the end credits. Once you've done that you can go back to Kodi and the next episode will appear in the Watching list but this is nothing short of infuriating when you have several different shows in-progress.

Please could you fix the add-on so that it : 
a) Marks shows as "in-progress" on the BBC site when you start to watch something new using the Kodi add-on.
b) Marks shows as "watched" on thee BBC site when watched on the Kodi add-on so that the "Watching" list updates as it should.

### PR DESCRIPTION
**Pull request by dimkroon**
Full 2-way sync of watching status and functionality aligned with the iplayer website.

Watching now displays a list of episodes, rather than series.
Context menu option to view all episodes.
Context menu option to remove an item from 'watching'.
Playing a video from watching now plays from the resume point obtained from the BBC.
While playing any video it's play state is send to the BBC, enabling to continue watching on another device. It fails silently and stops when a user is not signed in.

fixes #349

This PR implements the recently changed data returned by iplayer, is a bit re-structured, but is functional the same as the previous PR. 
Because the new data structure is also used in other listings, like Added and Recommended, there is now a parser function ParseEpisode() in ipww_video to handle this data. (At the moment Added is broken and this function could be used in a fix.)
All parsing specific to Continue Watching is now done in it's own function. 

The general idea is still the same:

**watching list**
ListWatching has it's own parser. To be honest, just because the general ParseJson() is too complex for me to comprehend and I had no idea where to fit in the new code.
The parser obtains the resume point and total playing time of the programme. Parameters and a callback argument are added, just to drag these through all functions and callbacks, supporting both manual and automatic stream selection. AddMenuEntry() will eventually set the resume point and total time as ListItem properties when it is called to add a playable.

**Play progress reports**
Progress reports send to the BCC require both programmeId and streamId. These are obtained in various parsers, and by the aid of new function and callback arguments eventually reach PlayStream(). After PlayStream() has passed the resolved url to Kodi it now keeps the addon running and starts to monitor play progress until the stream stops.

**FileProgress**
A attempt to monitor the state of a single stream and post status events to BBC just like a regular web browser. Special care is taken to handle the situation where a user starts another stream without stopping the previous one. (Kodi calls Resume() while the payer is playing and does not call Stop() at all)

### CODE REVIEW

**Comment by CaptainTK** [comment]
Thanks a lot for this comprehensive PR. I will release it in 4.1.0. This will be the first second digit version increase (new functionality) in 8 years!

Do you prefer your Github user name or your Kodi forum user name in the credits?

**Comment by dimkroon** [comment]
Thanks, I prefer GitHub username if it's all the same to you.
I've been working to more or less complete BCCiD integration on the iplayer side of the addon (which fixes the now broken 'added'). May it would be nice to include that 4.1, but I need some help to finish it.
I'll open an PR so you can have a look.

**Comment by CaptainTK** [comment]
Sure. Looking forward to your PR. I should have some time on the weekend to look at it in case you manage to open it by then.

**Comment by kevwag** [comment]
@dimkroon  Am I missing something here? Since the update I get nothing whatsoever in the "Continue watching" or "My List" menus and nothing is syncing. I'm using the latest version and I've tried signing out and back in again.

**Comment by dimkroon** [comment]
As far as I'm aware, no new release has been published since this PR was merged. If you cloned from github and installed from zip file it should work though. If not, please create a new debug log and post a link.
Search the kodi wiki for 'debug log' for info on how to do that.

14 apr. 2024 12:37:26 Kevin Wagener ***@***.***>:

**Comment by kevwag** [comment]
@dimkroon I've done that now and WOW! That is EXACTLY what I was asking for! Perfect! Thank you massively for all your hard work!

**Comment by CaptainTK** [comment]
Apologies for the long delay in releasing this. I am finally on it now.

**Comment by dimkroon** [comment]
No worries, I totally understand. I've been rather  busy myself the past months and seen my totdo list only grow.

21 apr. 2024 12:01:49 CaptainTK ***@***.***>:

**Pull request merged**
