### PR TITLE
Radio

### PR DESCRIPTION
**Pull request by primaeval**
Give this a go. That was a hell of a lot more work than I expected. I'll send you an invoice later. ;)

### CODE REVIEW

**Comment by CaptainTK** [comment]
I am surprised how quickly you did this. I wouldn't have the time. I am officially impressed.

Anyways: Please squash the commits for the PR and please create the PR against the development branch. I would like to clean up the whole thing before a release and keep the current master in case it needs bug fixes.

**Comment by primaeval** [comment]
I can't work out how to squash commits. I've tried Git Extensions but nothing seems to work. I need an easy guide.

**Comment by CaptainTK** [comment]
I think this should work:

1. Fork the development branch.
2. Merge your changes to this fork. During the merge you can squash commits on the command line.
3. Create a PR after the successful merge.

**Comment by primaeval** [comment]
I used Git Extensions merge with advanced options squah commits in the end. Git can get complicated pretty quickly.

**Pull request closed without merging**
