### PR TITLE
Added HTTP stream-proxy support

### PR DESCRIPTION
**Pull request by jhol**
Support for per-stream proxies has been included since Kodi commit
61d6149e. This patch adds support for this feature.

### CODE REVIEW

**Comment by CaptainTK** [comment]
Sorry, proxies will not be included.

**Comment by jhol** [comment]
That's a shame. It can be quite useful for Brits in restrictive networks, and Brits who travel a lot with work- which is my use case.

Oh well, I can probably maintain a non-hostile fork rebasing on master.

**Comment by CaptainTK** [comment]
I understand that there are legitimate reasons to use proxies. Restrictive networks certainly qualify, travel overseas for work most likely does not qualify in the eyes of the Beeb.

Long story short: The risk of abuse by end users and subsequent legal action against the add-on is simply too great for this feature to be included. If you want to keep your own fork, that is of course up to you.

**Comment by primaeval** [comment]
@jhol I tested it out but it wouldn't actually play the streams for me. Does it work for you? The actual resolved m3u8 seems to need to be proxied. Even setting the Kodi proxy to the same didn't work. I'm keeping it in my fork for learning purposes. Thanks.

**Comment by jhol** [comment]
@primaeval do you have an up to date nightly build of kodi? I only got the proxy patches accepted to git master last week

**Comment by primaeval** [comment]
@jhol I just tried it on KodiSetup-20160327-2d05a88-master.exe. It doesn't work from outside the UK for me. I think the hls streams are geo-checking every .ts packet. Looks like its vpn or smart dns only for hls streams. I was just using a free anonymous proxy to test.

**Comment by jhol** [comment]
@primaeval do you know if that is built with the latest release of FFMPEG? Because I had to patch there also.

If you look at Wireshark, you should see it routing both the playlist and the ts chunks through the proxy - but this is only possible since my upstream changes to Kodi and ffmpeg.

**Comment by primaeval** [comment]
@jhol Maybe its not in my win32 build.
```
Starting Kodi (17.0-ALPHA1 Git:20160327-2d05a88). Platform: Windows NT x86 32-bit
Using Release Kodi x32 build
Kodi compiled Mar 28 2016 by MSVC 180030723 for Windows NT x86 32-bit version 6.0 (0x06000000)

```
Do you need to enable the Kodi proxy as well or just the addon proxy to route the ts chunks?

**Comment by jhol** [comment]
@primaeval that build seems to include my patches to xbmc. 

I checked ffmpeg. That package has `avformat-56.dll` - I'm not sure what ffmpeg version that corresponds to, but it won't work unless it's late enough to include [this patch](https://git.videolan.org/gitweb.cgi/ffmpeg.git/?a=commit;h=c48122d731be09db054befac8ab0ef47fd7d4dc2). I'm not sure if they've bumped the ffmpeg version in the windows build - so that would be something to check.

**Comment by primaeval** [comment]
@jhol Should it work in Linux? I don't drink the apple kool-aid. ;)

**Comment by jhol** [comment]
@primaeval I only use Linux myself. It should work if you build the latest release of ffmpeg from source, then grab the Kodi git master and build that. You will need to specify the ffmpeg install path with `./configure`, otherwise it will pick up the system version, or attempt to build its own version from source.

That should work - or at least I had something like this while I was developing these patches.

**Comment by primaeval** [comment]
@jhol Did you get the hls iplayer streams to play from outside the uk?

**Comment by jhol** [comment]
@primaeval yeah it works - and it should do because all the BBC sees is the proxy.

**Pull request closed without merging**
