### PR TITLE
top level icons

### PR DESCRIPTION
**Pull request by primaeval**
Here are a few icons to try out and see if you like them. They are via Meta4Kodi (see the license file for the sources in Media).
I have added a warning setting for the Red Button dialog because I have a new addon that needs to scan folders for tv streams and the dialog stops it working. It uses RPC to scan the folders which is what is used on remote control apps like Yatze on Android.
https://github.com/primaeval/plugin.video.tvlistings.xmltv

### CODE REVIEW

**Comment by primaeval** [comment]
Here is a separate red button bitrate setting. High bitrate red button streams fail a lot.

**Comment by vonH** [comment]
I like it. 

I'm working on some 512x512 top level icons for general use that match the BBC styleguide. Interested?

ps: been away from Kodi for a while, slowly trying to come back.

**Comment by primaeval** [comment]
Don't worry about matching the BBC, they probably hate us anyway. ;)

**Comment by vonH** [comment]
Oh I'm almost certain of it. However, all prior iPlayer add-ons have used matching icons to try and create a more of a "BBC look."

**Comment by primaeval** [comment]
If you've got the skills and the time then photoshop away.

**Comment by primaeval** [comment]
This last commit fixes the missing HD Red Button streams. If you don't add anything else please add this commit as quickly as you can to get a fix out.

**Comment by CaptainTK** [comment]
Sorry, been busy the last days and will be busy next week, so I planned to postpone merging this whole lot. I see your point about Red Button and will try to get an update out as soon as possible. Might just create another bugfix branch and push these two bits myself to keep this PR open and free of merge conflicts.

**Comment by primaeval** [comment]
Thanks. I'm still looking for the proper Red Button m3u8 manifest so that this fix isn't needed. We cheat and convert the f4m one to m3u8 at the moment.

**Comment by CaptainTK** [comment]
BTW: Please remove the debug log from the last commit.

**Comment by CaptainTK** [comment]
Yeah, same as for live TV. I don't like this hack, but I don't see any other option at the moment.

I created a pull request for 2.3.3 to be updated at the official repo. Let's hope they merge it quickly. Thanks very much for this! Great timing with Glastonbury on tonight.

**Comment by primaeval** [comment]
Thanks.

**Comment by primaeval** [comment]
This commit uses the proper red button manifesto. Akamai works fine but I get the geoblock message for Limelight. Could you check if it works for you. I can't test the sound right now because there isn't any.

**Comment by CaptainTK** [comment]
Limelight seems a bit sketchy, but I can get it to work. Perhaps the Beeb decided all counties that voted to remain are no longer part of the UK and thus iPlayer will be blocked, so you may need to move.

Let's wait till some real streams come online to test audio as well. Shouldn't be long.

**Comment by primaeval** [comment]
The drawbridge has come up fast. I don't like the racist mood in England from what I hear.
At least its nice to see some happy young people at Glastonbury, until they realise they are stuck in sunny England for the rest of their lives.

**Comment by CaptainTK** [comment]
Well, it is not much different from the racist mood in many other parts of Europe, isn't it?

I think most of the people at Glastonbury know full-well what has happened and just try to dance their worries away for a couple of days.

Back on topic: 2.3.4 is out and submitted to the official repo based on the bugfix branch.

**Comment by primaeval** [comment]
Thanks. I'm writing a little addon to try out all the stream combinations so it shouldn't take long to fix next time.

The majority party in government here in Denmark is far right since the last election. The mood is pretty bad here too. There is nothing like a good global recession to bring the resentment of foreigners out in people. There is lots of space left on Mars, so I hear. ;)

**Comment by primaeval** [comment]
Here you go. A little test addon that checks for every type of live tv stream. It uses f4mtester for the f4m streams. I don't think I'll make it pretty. It is just for testing and emergencies.
https://github.com/primaeval/plugin.video.bbc.live

**Comment by CaptainTK** [comment]
Why did you close it all of a sudden? I simply didn't get to do any work on the add-on lately.

**Comment by primaeval** [comment]
I'm redoing the changes and deleted one too many branches.

**Pull request closed without merging**
