### PR TITLE
playback failed notice

### PR DESCRIPTION
**Pull request by primaeval**
ZingZillas has clips but no episodes. Clips aren't scraped yet.

### CODE REVIEW

**Comment by CaptainTK** [comment]
Sorry, but what exactly is the issue with CBeeBies?

**Comment by primaeval** [comment]
Some of the CBeebies pages seem to have some special formatting like they do for video. The main issue is with having clips but no episodes, like with ZingZillas. If I come across something definite I'll post an example.

**Comment by primaeval** [comment]
Found one. Search for Cloudbabies Nighting Time and go to the episode group.

**Comment by CaptainTK** [comment]
OK, that really looks like an odd HTML page. I can see why this may take longer and an error message is appropriate.

**Comment by primaeval** [comment]
This helps for the episodes page. https://github.com/primaeval/plugin.video.iplayerwww/commit/e900f1aa796dec972014ad491b4a3620e1e02b76

**Comment by CaptainTK** [comment]
Just one thing: The error messages should be IDs starting with 304xx. Could you please change that and I will merge this all. Thanks.

**Comment by primaeval** [comment]
done

**Pull request merged**
