### PR TITLE
mediator fix

### PR DESCRIPTION
**Pull request by primaeval**
mediator fix from the forum https://forum.kodi.tv/showthread.php?tid=239378&pid=2629829#pid2629829

This is critical. Nothing works without it.

### CODE REVIEW

**Comment by CaptainTK** [comment]
Thanks, but I won't be able to release anything this week. With a fair bit of luck, I can get something out Sunday night.

**Comment by CaptainTK** [comment]
I managed to prepare and release everything on GitHub. Found some new software for my iPad. However, I doubt I will be able to create the PR to the official repo. If you could do me the honour once again @primaeval, that would be terrific.

**Comment by primaeval** [comment]
Can you remember how? I posted some notes somewhere.

**Comment by primaeval** [comment]
Done. I hope.

**Comment by CaptainTK** [comment]
You almost got it. One file too many.

Once this works out, can you please also open the PR for 2.5.22 inthe helix repo?

BTW, the How-To can be found [here](http://kodi.wiki/view/HOW-TO:Create_add-on_PRs_using_Git_Subtree_Merging).

**Comment by primaeval** [comment]
I did the helix one first. I have no idea how that license file got in there though. Strange.

**Comment by CaptainTK** [comment]
Ah thanks, I did not see that helix had already been merged.

**Pull request merged**
