### PR TITLE
Fix for #30 and #31 - Subtitles and Icons

### PR DESCRIPTION
**Pull request by ihurst**
This fix parses the new xml subtitles correctly. Example is Eastenders 02/11/2015

There appears to be another issue, which means once subtitles appear on one programme they will not appear on the next programme you go to. This includes restarting the same programme.

### CODE REVIEW

**Comment by ihurst** [comment]
The secondary issue is a little strange. It only occurs if you don't exit the current stream/programme before playing the next.

**Comment by ihurst** [comment]
Also added the other channel icons in this pull request. Note: Still missing s4c as not in other repository

**Comment by CaptainTK** [comment]
It is not surprising that subtitles will not work correctly if you don't exit the current programme. Simple reason: The file is still open in r- or rw-mode by Kodi, so it cannot be opened again in rw-mode to write the newly converted subtitles to it.

I don't think that's a bug.

**Comment by CaptainTK** [comment]
Thank you.

**Comment by ihurst** [comment]
Agree about not opening a bug for this. It is a little strange though as the correct .srt file does get updated/written correctly.  It just doesn't get loaded correctly.  I may spend a little time looking at it :-)

**Comment by CaptainTK** [comment]
I will certainly not complain if you want to investigate this further. :)

**Pull request merged**
