### PR TITLE
ListCategories href has more classes

### PR DESCRIPTION
**Pull request by primaeval**
This gets you back into the Categories list.

### CODE REVIEW

**Comment by CaptainTK** [comment]
Sorry, I just pushed 6c56236dd1670cc76f95a2260d253743cd566069 which essentially does the same.

**Comment by primaeval** [comment]
Good. That should do it.

**Comment by CaptainTK** [comment]
Yeah, lucky it was that easy. I was a little scared they might have messed up the whole HTML structure once again.

**Comment by primaeval** [comment]
I hope that was just a tweak rather than the start of a big change. They've done that before to us during a holiday week and messed everything up.

**Pull request closed without merging**
