### PR TITLE
new HLS HD streams

### PR DESCRIPTION
**Pull request by primaeval**
This is my final offer. I need to get on with other things.

TODO: 
- The bitrates from the different devices are so similar that you need to find a way to make them stand out in the Settings page.
- Some sort of error message if the bitrate is too low to be found.

### CODE REVIEW

**Comment by CaptainTK** [comment]
Thanks for this, @primaeval.

I merged it and did some modifications in 2e9b9656ee6159a10ee9663916ebe82bced3ef8a, especially regarding autoplay. Everything seems to work OK for me, but could you please also take a look and try if this works for you?

Since the new bitrates will break compatibility anyways, we may just as well reduce the number of options, what do you think?

**Comment by primaeval** [comment]
It works ok for me. Only two tiny things:

- Fastest implies the lowest bitrate because it is faster to download. Highest implies the larger bitrate. Users are getting confused too. http://forum.kodi.tv/showthread.php?tid=239378&pid=2267662#pid2267662

- The two 0.1Mbps could be confusing but are not going to cause any problems for almost everyone anyway. Changing the first to 0.0Mbps won't break anything but gives feedback that the change buttons work ok. 

https://github.com/primaeval/plugin.video.iplayerwww/commit/8abb9caf4532e0ac0626cc45532e570cc515b0d3

Here are my test results:

bitrate selected and stream match
```
0 [u'1', 1.8, u'mp4a.40.5,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa3%3d96000-video%3d1604000.norewind.m3u8', 'Akamai']
1 [u'1', 0.1, u'mp4a.40.5,avc1.66.21', u'192x108', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa1%3d24000-video%3d31000.norewind.m3u8', 'Akamai']
2 [u'1', 0.1, u'mp4a.40.5,avc1.66.21', u'192x108', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa1%3d24000-video%3d31000.norewind.m3u8', 'Akamai']
3 [u'1', 0.2, u'mp4a.40.5,avc1.66.21', u'256x144', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa2%3d48000-video%3d156000.norewind.m3u8', 'Akamai']
6 [u'1', 1.0, u'mp4a.40.5,avc1.77.30', u'704x396', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa3%3d96000-video%3d827000.norewind.m3u8', 'Akamai']
7 [u'1', 1.8, u'mp4a.40.5,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa3%3d96000-video%3d1604000.norewind.m3u8', 'Akamai']
8 [u'1', 1.8, u'mp4a.40.5,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa3%3d96000-video%3d1604000.norewind.m3u8', 'Akamai']
9 [u'1', 1.8, u'mp4a.40.5,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa3%3d96000-video%3d1604000.norewind.m3u8', 'Akamai']

0 [u'1', 5.5, u'mp4a.40.2,avc1.100.32', u'1280x720', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d5070000.m3u8', 'Akamai']
1 [u'1', 1.0, u'mp4a.40.2,avc1.77.30', u'704x396', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d827000.m3u8', 'Akamai']
2 [u'1', 1.0, u'mp4a.40.2,avc1.77.30', u'704x396', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d827000.m3u8', 'Akamai']
3 [u'1', 1.0, u'mp4a.40.2,avc1.77.30', u'704x396', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d827000.m3u8', 'Akamai']
6 [u'1', 1.0, u'mp4a.40.2,avc1.77.30', u'704x396', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d827000.m3u8', 'Akamai']
7 [u'1', 1.8, u'mp4a.40.2,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d1604000.m3u8', 'Akamai']
8 [u'1', 3.1, u'mp4a.40.2,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d2812000.m3u8', 'Akamai']
9 [u'1', 5.5, u'mp4a.40.2,avc1.100.32', u'1280x720', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d5070000.m3u8', 'Akamai']


```

Effects of bitrate rounding (before and after):

```
[
[u'1', u'1012300', u'mp4a.40.2,avc1.77.30', u'704x396', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d827000.m3u8', 'Akamai'], 
[u'1', u'1835920', u'mp4a.40.2,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d1604000.m3u8', 'Akamai'], 
[u'1', u'3116400', u'mp4a.40.2,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d2812000.m3u8', 'Akamai'], 
[u'1', u'5509880', u'mp4a.40.2,avc1.100.32', u'1280x720', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d5070000.m3u8', 'Akamai'], 

[u'1', u'1012300', u'mp4a.40.2,avc1.77.30', u'704x396', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d827000.m3u8', 'Limelight'], 
[u'1', u'1835920', u'mp4a.40.2,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d1604000.m3u8', 'Limelight'], 
[u'1', u'3116400', u'mp4a.40.2,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d2812000.m3u8', 'Limelight'], 
[u'1', u'5509880', u'mp4a.40.2,avc1.100.32', u'1280x720', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d5070000.m3u8', 'Limelight']]



[
[u'1', 1.0, u'mp4a.40.2,avc1.77.30', u'704x396', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d827000.m3u8', 'Akamai'], 
[u'1', 1.8, u'mp4a.40.2,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d1604000.m3u8', 'Akamai'], 
[u'1', 3.1, u'mp4a.40.2,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d2812000.m3u8', 'Akamai'], 
[u'1', 5.5, u'mp4a.40.2,avc1.100.32', u'1280x720', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d5070000.m3u8', 'Akamai'], 

[u'1', 1.0, u'mp4a.40.2,avc1.77.30', u'704x396', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d827000.m3u8', 'Limelight'], 
[u'1', 1.8, u'mp4a.40.2,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d1604000.m3u8', 'Limelight'], 
[u'1', 3.1, u'mp4a.40.2,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d2812000.m3u8', 'Limelight'], 
[u'1', 5.5, u'mp4a.40.2,avc1.100.32', u'1280x720', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d5070000.m3u8', 'Limelight']]


[
[u'1', u'978380', u'mp4a.40.5,avc1.77.30', u'704x396', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa3%3d96000-video%3d827000.norewind.m3u8', 'Akamai'], 
[u'1', u'58300', u'mp4a.40.5,avc1.66.21', u'192x108', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa1%3d24000-video%3d31000.norewind.m3u8', 'Akamai'], 
[u'1', u'116600', u'mp4a.40.5,avc1.66.21', u'192x108', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa1%3d24000-video%3d86000.norewind.m3u8', 'Akamai'], 
[u'1', u'216240', u'mp4a.40.5,avc1.66.21', u'256x144', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa2%3d48000-video%3d156000.norewind.m3u8', 'Akamai'], 
[u'1', u'348740', u'mp4a.40.5,avc1.66.21', u'384x216', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa2%3d48000-video%3d281000.norewind.m3u8', 'Akamai'], 
[u'1', u'564980', u'mp4a.40.5,avc1.66.30', u'512x288', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa3%3d96000-video%3d437000.norewind.m3u8', 'Akamai'], 
[u'1', u'1802000', u'mp4a.40.5,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa3%3d96000-video%3d1604000.norewind.m3u8', 'Akamai'], 

[u'1', u'978380', u'mp4a.40.5,avc1.77.30', u'704x396', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa3%3d96000-video%3d827000.norewind.m3u8', 'Limelight'], 
[u'1', u'58300', u'mp4a.40.5,avc1.66.21', u'192x108', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa1%3d24000-video%3d31000.norewind.m3u8', 'Limelight'], 
[u'1', u'116600', u'mp4a.40.5,avc1.66.21', u'192x108', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa1%3d24000-video%3d86000.norewind.m3u8', 'Limelight'], 
[u'1', u'216240', u'mp4a.40.5,avc1.66.21', u'256x144', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa2%3d48000-video%3d156000.norewind.m3u8', 'Limelight'], 
[u'1', u'348740', u'mp4a.40.5,avc1.66.21', u'384x216', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa2%3d48000-video%3d281000.norewind.m3u8', 'Limelight'], 
[u'1', u'564980', u'mp4a.40.5,avc1.66.30', u'512x288', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa3%3d96000-video%3d437000.norewind.m3u8', 'Limelight'], 
[u'1', u'1802000', u'mp4a.40.5,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa3%3d96000-video%3d1604000.norewind.m3u8', 'Limelight']]


[
[u'1', 1.0, u'mp4a.40.5,avc1.77.30', u'704x396', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa3%3d96000-video%3d827000.norewind.m3u8', 'Akamai'], 
[u'1', 0.1, u'mp4a.40.5,avc1.66.21', u'192x108', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa1%3d24000-video%3d31000.norewind.m3u8', 'Akamai'], 
[u'1', 0.1, u'mp4a.40.5,avc1.66.21', u'192x108', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa1%3d24000-video%3d86000.norewind.m3u8', 'Akamai'], 
[u'1', 0.2, u'mp4a.40.5,avc1.66.21', u'256x144', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa2%3d48000-video%3d156000.norewind.m3u8', 'Akamai'], 
[u'1', 0.3, u'mp4a.40.5,avc1.66.21', u'384x216', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa2%3d48000-video%3d281000.norewind.m3u8', 'Akamai'], 
[u'1', 0.6, u'mp4a.40.5,avc1.66.30', u'512x288', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa3%3d96000-video%3d437000.norewind.m3u8', 'Akamai'], 
[u'1', 1.8, u'mp4a.40.5,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.edgesuite.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa3%3d96000-video%3d1604000.norewind.m3u8', 'Akamai'], 

[u'1', 1.0, u'mp4a.40.5,avc1.77.30', u'704x396', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa3%3d96000-video%3d827000.norewind.m3u8', 'Limelight'], 
[u'1', 0.1, u'mp4a.40.5,avc1.66.21', u'192x108', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa1%3d24000-video%3d31000.norewind.m3u8', 'Limelight'], 
[u'1', 0.1, u'mp4a.40.5,avc1.66.21', u'192x108', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa1%3d24000-video%3d86000.norewind.m3u8', 'Limelight'], 
[u'1', 0.2, u'mp4a.40.5,avc1.66.21', u'256x144', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa2%3d48000-video%3d156000.norewind.m3u8', 'Limelight'], 
[u'1', 0.3, u'mp4a.40.5,avc1.66.21', u'384x216', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa2%3d48000-video%3d281000.norewind.m3u8', 'Limelight'], 
[u'1', 0.6, u'mp4a.40.5,avc1.66.30', u'512x288', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa3%3d96000-video%3d437000.norewind.m3u8', 'Limelight'], 
[u'1', 1.8, u'mp4a.40.5,avc1.100.31', u'960x540', u'http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa3%3d96000-video%3d1604000.norewind.m3u8', 'Limelight']]
```

**Comment by CaptainTK** [comment]
> Fastest implies the lowest bitrate because it is faster to download. Highest implies the larger bitrate. Users are getting confused too. http://forum.kodi.tv/showthread.php?tid=239378&pid=2267662#pid2267662

I tend to agree, but Highest also caused some confusion in the past. I originally used Highest, but @cas-- introduced Fastest instead.

> The two 0.1Mbps could be confusing but are not going to cause any problems for almost everyone anyway. Changing the first to 0.0Mbps won't break anything but gives feedback that the change buttons work ok. 

0.0 seems wrong to me. There is no stream with that bitrate. I would rather dump 0.0 and change the number of values. All users using autoplay will have to reset this value anyways with an update.

**Comment by primaeval** [comment]
Cas was wrong. ;)
I don't like 0.0 either but it would leave the total at 10 choices. You could also rename it to live_bitrate2 which would force a new default to Highest.

**Comment by CaptainTK** [comment]
> You could also rename it to live_bitrate2 which would force a new default to Highest.

I thought about that, too. Seems like a dirty workaround, though.

**Comment by primaeval** [comment]
The lowest could be 0.05 which wouldn't select anything but looks better than 0.0.

**Comment by CaptainTK** [comment]
Sounds like we should have a special treatment for the 0.06 Mbps streams?

I don't understand why they are supplied at all. Who wants to watch at 192x108 pixels resolution? Better to go for radio right away. Ah, wait: Radio bitrate is more than 0.06 Mbps. :-)

**Pull request merged**
