### PR TITLE
Testing of the new login mechanism

### PR DESCRIPTION
**Pull request by ihurst**
Moving towards solving #128. I think the login code does not actually work. I've also had to create  a little stand-alone test script "LoginTest" which should be quite simple to understand and play with.

The main change has to be use a request.Session() which means each HTTP Request including redirects store their cookie in the session, so we get them all at the end. Though strange things are going on as I have to hit multiple URLs to get authentication to work correctly.

But this has then taken me to the point where I call some of the BBCiD content and this is just falling apart, see the ListWatching error below - which should be processing the JSON data coming back:

> Error Type: <type 'exceptions.AttributeError'>
> Error Contents: 'NoneType' object has no attribute 'get'
> Traceback (most recent call last):
> File "/storage/.kodi/addons/plugin.video.iplayerwww/default.py", line 124, in <module>
> Video.ListWatching(logged_in)
> File "/storage/.kodi/addons/plugin.video.iplayerwww/resources/lib/ipwww_video.py", line 912, in ListWatching
> watching_list = json_data.get('watching').get('elements')
> AttributeError: 'NoneType' object has no attribute 'get'

As I mentioned I am going to be unavailable for at least a week, so I'll have a quick look at this now, but don't think I'll complete. I should be picking up e-mail for discussions.

### CODE REVIEW

**Comment by ihurst** [comment]
Sorry I need to remember how to use git and github again, but hopefully this gives you access to what I'm doing.

**Comment by ihurst** [comment]
The watching API stuff does look awful. We use to get this content from the following url:

 >https://ibl.api.bbci.co.uk/ibl/v1/user/watching?identity_cookie=%s

But we do not have an IDENTITY cookie any more (new login stuff) and if I try and visit the above I get the following error:

>{"version":"1.0","schema":"/ibl/v1/schema/ibl.json","error":{"details":"Missing authorization header","http_response_code":401}}

So the service is still there, just need to work out how to authenticate with it... forgotten how I worked all this out last time. But it must have been just from the main iPlayer web-site.

**Comment by ihurst** [comment]
Interesting near bottom of page: http://forum.kodi.tv/showthread.php?tid=51322&page=172

Done for the night.

**Comment by CaptainTK** [comment]
Thanks a lot for this! Getting the login right should be 80% of the work done.

From your description, it seems like they switched to a full Nitro API for the JSON responses. We will not be able to obtain a valid and licensed identity cookie for this API, so good bye JSON. My guess is that we will need to scrape the web pages like for everything else. This will be some annoying work to do, but it should not be a major issue.

**Comment by ihurst** [comment]
Nice to get involved again. I think you're right that you should just be able to do normal scraping, just a shame about extra work.

There is an issue with signout. Just change the URL to match my test client. Though when I tested it doesn't actually log out, clearing cookies will fix this client side but maybe found a bbc issue?!?

**Pull request merged**
