### PR TITLE
get name,image,description from episode page

### PR DESCRIPTION
**Pull request by primaeval**
Hi. One more pull request for today. Could you add this please.
It will get the name, image and description from the episode page if it can find them.
The reason is so that I can make a pull request to Kore.
I've modified the Play On Kodi intent in Kore to pick up iplayer episode urls and play them with iplayerwww. The name, image and description need to be scraped in the addon as the intent only deals with the url.
Here is my "local" branch of Kore with the last 2 commits doing the work.
https://github.com/primaeval/Kore/tree/local
and here is a built apk if you want to test it.
https://github.com/primaeval/assets/tree/master/apk

### CODE REVIEW

**Comment by primaeval** [comment]
It needs some better fallback searches for name, image and description. I think the ones I tested with were all in the apple store. Others aren't. I'll have a look tomorrow.

**Comment by primaeval** [comment]
This last commit lets you add a link to Favourites for Dash streams.

**Comment by primaeval** [comment]
I wondered what you were up to because you merged the Krypton stuff into master. I just followed that.

**Comment by CaptainTK** [comment]
I didn't do that on purpose, it happened without warning when merging your last changes from master to krypton. Somehow resolving the merge conflicts must have messed up everything.

**Comment by primaeval** [comment]
It's easier programming in python than working out how to get git to do stuff sometimes. ;)

**Comment by primaeval** [comment]
I did a hard reset on this PR and opened a new one for krypton

**Comment by CaptainTK** [comment]
I just fixed the master branch with a hard reset and forced push. Unfortunately, this means that your master is out of sync and this PR would merge the just fixed parts back into master.

Please rebase your master to see if this fixes the PR, @primaeval. Sorry for the mess, I still don't understand why there were changes from krypton merged into master in the first place.

**Comment by primaeval** [comment]
I think this fixes it. I hard reset to your master and cherry picked my 3 commits.
I tested quite a few programs and most seem to get the extra info from these meta og: tags but you should make sure yourself. I might have been lucky.

**Pull request merged**
