### PR TITLE
BBCiD bugs v2

### PR DESCRIPTION
**Pull request by primaeval**
I found a couple of bugs with BBCiD.
The confirmation page doesn't have a full stop.
If your episode has lost the plot CheckAutoplay bombs out. Here is an example:
http://www.bbc.co.uk/iplayer/episode/b06g0x7s/formula-1-2015-qualifying-replay-japan
I haven't put in code to fix all potentially missing fields but I can see them causing bugs in the future.

### CODE REVIEW

**Comment by ihurst** [comment]
Thanks for looking at these. Sorry been away this weekend. I can have a look at any outstanding issues.

**Comment by ihurst** [comment]
Was worried these issues were all due to the BBCiD work I did, but looks like more general issues.

I'd like to spend some time trying splitting the code out into seperate files/classes rather than the single default.py file. Has anyone got any thoughts on this?

**Comment by primaeval** [comment]
My opinion: KISS. Or you end up with a Java-esque monster with millions of itty bitty files and classes.

**Comment by ihurst** [comment]
Probably showing my Java background then ;-) I won't go down this path then.

**Pull request merged**
