### PR TITLE
shortened stream kind and fallback

### PR DESCRIPTION
**Pull request by primaeval**
There is a new stream kind called shortened.
The else statement should catch any new kinds they introduce.
I don't think that should cause a problem as it is after the ad and signed tests.

### CODE REVIEW

**Comment by CaptainTK** [comment]
Thanks for the new stream kind. I am not sure I like the default for all new stream kinds. If it was that simple we could just check for AD and signed first and then handle everything else.

Why not raise an error message which includes the (new) stream kind?

Anyways, I can release a fix tonight.

**Comment by primaeval** [comment]
Have you seen a kind that would mess something up?

**Comment by CaptainTK** [comment]
I feel like I have, but I can't nail it. :-/

**Comment by primaeval** [comment]
It's your call of course but I would say the wrong stream is better than no stream.

**Comment by CaptainTK** [comment]
I'll add a print for debug reasons. In case something breaks we should be able to see it easily in the debug log.

**Pull request merged**
