### PR TITLE
spaces are now new lines

### PR DESCRIPTION
**Pull request by primaeval**
fixes MostPopular via GetGroups

### CODE REVIEW

**Comment by CaptainTK** [comment]
That's an annoying change and shows what I don't like about regexps.

I just wanted to merge, but then got more changes than before including a debug print. So I assume this is still WIP and will wait with the merge.

**Comment by primaeval** [comment]
There are 2 commits that seem to fix everything now.

**Comment by primaeval** [comment]
1 more commit for search.

**Comment by CaptainTK** [comment]
Please remove or comment the print in line 253 and we're good to merge. Sorry for being so annoying, but I really don't even have a text editor with me.

On a side note: I think changing from space to any characters can cause even more problems, but then this is just a short term fix before the redesign.

**Comment by primaeval** [comment]
Fixed. 
I added the any char regex in case they add other attributes before the ones we want.

**Comment by primaeval** [comment]
If you want a robust design with speed I think a hybrid soup/regex function might work. 

In my regex branch in ScrapeEpisodes, after I split the html at list_items, you could try souping just that bit of html. Same for the singles and groups from inner_anchors in ListHighlights. 

I'm happy with my regex branch so I'm sticking with that for now.

**Comment by CaptainTK** [comment]
Thanks.

Fixes #43.

**Pull request merged**
