### PR TITLE
Radio - Squashed commit of the following:

### PR DESCRIPTION
**Pull request by primaeval**
commit 88a2dab0518d50e124faad3c397b62859374a660
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Wed Feb 3 13:17:39 2016 +0100

    tidy

commit e3e826228437d91a54b249c78de454dadfa5e48e
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Wed Feb 3 13:01:34 2016 +0100

    radio live autoplay

commit c26a8245349ec294e6924572be4d219a55c44892
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Wed Feb 3 12:45:59 2016 +0100

    radio catchup autoplay

commit 2d9b2c4fb7f9b30d19794fdcc1c6effd9c9e50e0
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Wed Feb 3 10:23:41 2016 +0100

    radio search episode titles

commit 561d7432145765c4137c93688bf52a88b59d5a12
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Wed Feb 3 10:14:07 2016 +0100

    radio genre pagination

commit 007f0433d2024b4952b5972a3714d92fca3121e1
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Wed Feb 3 09:53:55 2016 +0100

    radio a-z pagination

commit 8881ee1bc418f54acc36a29d0e99017f3e4ac0fd
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Wed Feb 3 09:32:43 2016 +0100

    radio a-z fix

commit 70b17a664b69a7b6281c91782302a0393f40332a
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Tue Feb 2 17:56:56 2016 +0100

    radio favourites

commit b3d33d7367a1bd6a09605e0a41b6735e70a63016
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Tue Feb 2 16:40:56 2016 +0100

    radio most popular

commit 6b7644a2d219a78bda8fa197379012d51e1ce05c
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Tue Feb 2 15:24:12 2016 +0100

    radio search

commit cf346b0daa15c0a82f598d2f6d92bbaae2983c77
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Tue Feb 2 10:11:15 2016 +0100

    radio genres and audio/visual addon split

commit bb0f8a9985d67838586bd6c282a85589aad0ee12
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Mon Feb 1 18:55:09 2016 +0100

    fixed radio channel names

commit ab86d82ea1d49177a4847532bc8ee6376d6be263
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Mon Feb 1 18:38:07 2016 +0100

    live radio working (some channels are wrong)

commit 909e3a61fb537e9d584b97b1d106c6496c364154
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Sun Jan 31 17:11:50 2016 +0100

    radio episode pagination

commit bd1eab7173fdb2eef577b8d81518763c2c64e3e8
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Sun Jan 31 15:15:05 2016 +0100

    radio a-z basic pagination

commit 8d733418004661f6eef716e93f0b4a447fff9dc5
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Sun Jan 31 10:34:13 2016 +0100

    radio bitrate simplification

commit b424e6278ccf1f4b46c3adb1105ae2b7dcae218c
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Sun Jan 31 09:13:49 2016 +0100

    radio streams play :)

commit 0473e52f0923e97cdb4cdbc6322f2f7bf67b01f2
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Sat Jan 30 16:11:02 2016 +0100

    scrape radio episodes

commit c2b7ebd2db449942889f85934795474909ef05b9
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Sat Jan 30 11:19:08 2016 +0100

    radio scraping (scafolding)

commit ff07976bc59780abbab7373025ad694a0b03fe0f
Author: primaeval <primaeval@users.noreply.github.com>
Date:   Sat Jan 30 10:35:31 2016 +0100

    starting radio with a-z

### CODE REVIEW

**Comment by CaptainTK** [comment]
Thank you.

Still some work to do, though. I already have some ideas for simplification.

**Comment by primaeval** [comment]
There are about 4 or 5 scraping functions which are similar but not quite. I expect they can be combined with a bit of thought but the functionality needs to be tested first.

**Comment by CaptainTK** [comment]
I also think that some functions can be shared between radio and video. Genres should be scraped instead of being static. Then I want to separate video and audio into different .py files...

**Comment by primaeval** [comment]
I didn't scrape Genres because some of the radio pages are painfully slow. I don't think people go there that often so they are not cached but are generated by the server in a queue. Be careful combining audio and video functions. There are so many subtle differences that I found it easier just to keep them seperate.

**Comment by CaptainTK** [comment]
OK, if there is such a darmatic performance hit for Genres, it might be better to use a list.

I was thinking of things like CheckAutoplay, which just needs an additional paramter and you can already save a function. But perhaps you are right to keep them separate. Once radio and video are moved to different source files, it should at least get easier to maintain.

**Comment by primaeval** [comment]
The trouble with polishing this is that the BBC could just change everything overnight and break the lot. That's probably why the old iplayer addon team gave up. It's probably best to think of this as temporary, almost throw-away scripts to keep yourself sane.

**Comment by CaptainTK** [comment]
I tend to agree. Still, there will be dozens of small fixes required every now and then and keeping everything in one source code file just makes things more difficult to maintain.

Don't worry, I have no desire to overengineer this. My only concern is making sure maintenance is easy and also that different contributors can work on different parts (radio, video) in parallel without the need for complicated merges.

**Comment by CaptainTK** [comment]
OK, I broke it down into a few files. This should make life a little easier, although it is far from perfect.

One thing that annoys me is this: I use a shortcut for the add-on, so I don't need to navigate through Video->Add-ons->iPlayer WWW all the time. Since the add-on provides both video and audio, this does not work any more. It seems like Kodi did not set the content_type in this case.

**Comment by primaeval** [comment]
That is a wierd kodi bug. I had a video shortcut that worked. Then I added a music shortcut and both didn't work. But when I got rid of the music shortcut the video one won't work any more. Strange.
The only fix I can think of is to make a totally seperate radio addon. But that is a bit drastic.

**Comment by primaeval** [comment]
Actually the addon zip file can contain 2 plugins: plugin.video.iplayerwww and plugin.audio.iplayerwww. It's not as elegant as content_type but it should work.

**Comment by CaptainTK** [comment]
That doesn't sound like a good solution to me. I will rather try rto get back to one working shortcut and open a ticket for this to be fixed in Kodi.

**Comment by primaeval** [comment]
I'm not sure there is even a concept of plugin type in the shortcut buttons. I tried the re-touched skin and it didn't even seperate video and audio. It does work correctly from the Favourites menu though.

**Comment by primaeval** [comment]
What you can do is either have a combined menu or a top level menu of TV/Radio if there is no content_type setting.

**Comment by primaeval** [comment]
Like this: https://github.com/primaeval/plugin.video.iplayerwww/commit/251a0c7daed4a870b6ccd4cac366ba8837f06796

**Comment by CaptainTK** [comment]
That's an interesting idea. However, I think it should be an extra menu which allows users to choose video or radio manually. What do you think?

**Comment by primaeval** [comment]
I use it so much that I would just like to get to the full menu as soon as possible. Maybe use a dividing line or colours to make it obvious. The TV sections will have to be preceded by "TV" to make it obvious which is which.

**Comment by CaptainTK** [comment]
I integrated something like that into the development branch today.

I also added translations for radio and tried to reuse as much of the TV text that were already available.

Finally, I also scraped the Radio Categories from the website. This does not take much time and should also allow new Categories to appear automatically.

**Comment by primaeval** [comment]
Sounds good. Thanks for the comments in the forum.

**Comment by primaeval** [comment]
Something is wrong:
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'AddAvailableStreamItem'
                                            Traceback (most recent call last):
                                              File "C:\Kodi15.2\portable_data\addons\plugin.video.iplayerwww\default.py", line 265, in <module>
                                                Radio.AddAvailableStreamItem(name, url, iconimage, description)
                                            AttributeError: 'module' object has no attribute 'AddAvailableStreamItem'
```

**Comment by CaptainTK** [comment]
Uuuups. Must have deleted that while breaking up the code. Try again, please.

**Comment by primaeval** [comment]
Seems ok now...but CheckLogin is missing for the Favourites.
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'CheckLogin' is not defined
                                            Traceback (most recent call last):
                                              File "C:\Kodi15.2\portable_data\addons\plugin.video.iplayerwww-development\default.py", line 185, in <module>
                                                Video.ListFavourites(logged_in)
                                              File "C:\Kodi15.2\portable_data\addons\plugin.video.iplayerwww-development\resources\lib\ipwww_video.py", line 883, in ListFavourites
                                                if(CheckLogin(logged_in) == False):
                                            NameError: global name 'CheckLogin' is not defined
```

**Comment by CaptainTK** [comment]
Fixed. Thanks.

**Comment by primaeval** [comment]
There is a bit more to do ;)
```
18:19:22 T:3780   ERROR: C:\Kodi15.2\portable_data\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
18:19:22 T:3780   ERROR: C:\Kodi15.2\portable_data\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
18:19:24 T:3780   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'ADDON' is not defined
                                            Traceback (most recent call last):
                                              File "C:\Kodi15.2\portable_data\addons\plugin.video.iplayerwww-development\default.py", line 206, in <module>
                                                Radio.ListFavourites(logged_in)
                                              File "C:\Kodi15.2\portable_data\addons\plugin.video.iplayerwww-development\resources\lib\ipwww_radio.py", line 663, in ListFavourites
                                                if(Common.CheckLogin(logged_in) == False):
                                              File "C:\Kodi15.2\portable_data\addons\plugin.video.iplayerwww-development\resources\lib\ipwww_common.py", line 178, in CheckLogin
                                                elif ADDON.getSetting('bbc_id_enabled') != 'true':
                                            NameError: global name 'ADDON' is not defined
                                            -->End of Python script error report<--
18:19:24 T:3804   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.iplayerwww/?description&iconimage&logged_in=False&mode=117&name=Radio%3a%20Favourites&subtitles_url&url=url
18:19:24 T:3804   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.iplayerwww/?description&iconimage&logged_in=False&mode=117&name=Radio%3a%20Favourites&subtitles_url&url=url) failed
18:19:24 T:3512  NOTICE: Thread LanguageInvoker start, auto delete: false
18:19:24 T:3512  NOTICE: -->Python Interpreter Initialized<--
18:19:24 T:4084  NOTICE: Thread BackgroundLoader start, auto delete: false
18:19:27 T:2392  NOTICE: Thread LanguageInvoker start, auto delete: false
18:19:28 T:2392  NOTICE: -->Python Interpreter Initialized<--
18:19:28 T:2392   ERROR: C:\Kodi15.2\portable_data\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
18:19:28 T:2392   ERROR: C:\Kodi15.2\portable_data\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
18:19:29 T:2392   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'ADDON' is not defined
                                            Traceback (most recent call last):
                                              File "C:\Kodi15.2\portable_data\addons\plugin.video.iplayerwww-development\default.py", line 185, in <module>
                                                Video.ListFavourites(logged_in)
                                              File "C:\Kodi15.2\portable_data\addons\plugin.video.iplayerwww-development\resources\lib\ipwww_video.py", line 883, in ListFavourites
                                                if(Common.CheckLogin(logged_in) == False):
                                              File "C:\Kodi15.2\portable_data\addons\plugin.video.iplayerwww-development\resources\lib\ipwww_common.py", line 178, in CheckLogin
                                                elif ADDON.getSetting('bbc_id_enabled') != 'true':
                                            NameError: global name 'ADDON' is not defined
```

**Comment by CaptainTK** [comment]
Thank you, this one should also be fixed.

As you can see, I still don't have a BBC ID, so I don't test this part of the code.

**Comment by primaeval** [comment]
BBC IDs are free, you know. ;)
Radio Favourites seems ok.
TV needs some more.
Are you regretting splitting the files yet? :)

```
18:51:50 T:3976   ERROR: C:\Kodi15.2\portable_data\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
18:51:50 T:3976   ERROR: C:\Kodi15.2\portable_data\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
18:51:53 T:3976   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'json' is not defined
                                            Traceback (most recent call last):
                                              File "C:\Kodi15.2\portable_data\addons\plugin.video.iplayerwww-development\default.py", line 186, in <module>
                                                Video.ListFavourites(logged_in)
                                              File "C:\Kodi15.2\portable_data\addons\plugin.video.iplayerwww-development\resources\lib\ipwww_video.py", line 889, in ListFavourites
                                                json_data = json.loads(html)
                                            NameError: global name 'json' is not defined
```

```
18:53:31 T:1584   ERROR: C:\Kodi15.2\portable_data\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
18:53:31 T:1584   ERROR: C:\Kodi15.2\portable_data\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
18:53:32 T:1584   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'cookie_jar' is not defined
                                            Traceback (most recent call last):
                                              File "C:\Kodi15.2\portable_data\addons\plugin.video.iplayerwww-development\default.py", line 183, in <module>
                                                Video.ListWatching(logged_in)
                                              File "C:\Kodi15.2\portable_data\addons\plugin.video.iplayerwww-development\resources\lib\ipwww_video.py", line 857, in ListWatching
                                                for cookie in cookie_jar:
                                            NameError: global name 'cookie_jar' is not defined
```

**Comment by CaptainTK** [comment]
Thanks once again. These two should be fixed as well.

No, I don't regret it. This was to be expected and it is the reason why I didn't want to make it a release right away. :-)

**Comment by primaeval** [comment]
Not yet.
```
19:06:16 T:1588   ERROR: C:\Kodi15.2\portable_data\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
19:06:16 T:1588   ERROR: C:\Kodi15.2\portable_data\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
19:06:21 T:1588   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'CATEGORIES' is not defined
                                            Traceback (most recent call last):
                                              File "C:\Kodi15.2\portable_data\addons\plugin.video.iplayerwww-development\default.py", line 210, in <module>
                                                Radio.ListFavourites(logged_in)
                                              File "C:\Kodi15.2\portable_data\addons\plugin.video.iplayerwww-development\resources\lib\ipwww_radio.py", line 664, in ListFavourites
                                                CATEGORIES()
                                            NameError: global name 'CATEGORIES' is not defined
```

```
19:07:11 T:1728   ERROR: C:\Kodi15.2\portable_data\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
19:07:11 T:1728   ERROR: C:\Kodi15.2\portable_data\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
19:07:16 T:1728   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'CATEGORIES' is not defined
                                            Traceback (most recent call last):
                                              File "C:\Kodi15.2\portable_data\addons\plugin.video.iplayerwww-development\default.py", line 189, in <module>
                                                Video.ListFavourites(logged_in)
                                              File "C:\Kodi15.2\portable_data\addons\plugin.video.iplayerwww-development\resources\lib\ipwww_video.py", line 885, in ListFavourites
                                                CATEGORIES()
                                            NameError: global name 'CATEGORIES' is not defined
                                            -->End of Python script error report<--
```

**Comment by CaptainTK** [comment]
That was a bad design from the start and still is. There should be an option in Kodi to return to the previous directory listing in case of an error without the need to recreate it. This basically creates a nested set of main menus, which makes no sense.

Anyways, I did a quick fix for it.

**Comment by primaeval** [comment]
Login successful, then failed.
```
20:30:10 T:3876   ERROR: C:\Kodi15.2\portable_data\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
20:30:10 T:3876   ERROR: C:\Kodi15.2\portable_data\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
```

**Comment by CaptainTK** [comment]
Sorry, I haven't got a clue. Do you have any more information on the line which triggers this error?

The whole login process was originally developed by @ihurst. Perhaps it is time to get back to him and ask him for some hints.

**Comment by primaeval** [comment]
It pretty sure its something to do with the scope of logged_in.

**Comment by CaptainTK** [comment]
Please take a look at Post 466 in the forum. If you select any bitrate for live other than "Fastest", the add-on will fail in radio. Unless there really are other bitrates than 128, I suggest to remove this selection for Radio.

**Comment by primaeval** [comment]
I thought the logic would fall through to any bitrate. I'll look again.
In post 466 the first line says radio one and the second says 1xtra. Did you see that?

**Comment by ihurst** [comment]
Primaeval,Sorry haven't looked at this for a long time, but the login fuctionality uses cookies (i.e. cookie lib part of urllib3) to keep the state of being logged in (i.e. a session).It will take me a little time to check the code out and find my way round, but happy to help if required.IanOn 07 February 2016 at 19:32 primaeval <notifications@github.com> wrote:Login successful, then failed.20:30:10 T:3876   ERROR: C:\Kodi15.2\portable_data\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
20:30:10 T:3876   ERROR: C:\Kodi15.2\portable_data\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning

**Comment by CaptainTK** [comment]
Regarding logged_in. That's a good point. Could you please try passing logged_in to each ipwww_* in default.py the same way as ADDON? You can find the relevant code in lines 25-29 of default.py. If this solves the issue, please let me know. Otherwise, I will need to look into global variables more closely again.

**Comment by CaptainTK** [comment]
On 466: You are absolutely correct, this is a different error. Nevertheless, the automatic stream selection is currently buggy. The problem is that it assumes the list of stream_bitrates is the same length as the options in settings.

**Comment by primaeval** [comment]
Can you fix the bitrates? According to this http://www.bbc.co.uk/blogs/internet/entries/d031b300-721a-4df5-8506-723303f2887e?comments_page=17&initial_page_size=10&filter=none&sortBy=LowestRating&sortOrder=Ascending the bitrates are:
/sbr_high/ = 320kbps
/sbr_med/ = 128kbps
/sbr_low/ = 96kbps
/sbr_vlow/ = 48kbps
but I did also see 60kbps somewhere.

**Comment by CaptainTK** [comment]
This will require separate settings for radio as the bitrates are obviously not the same as for TV and even the number of available bitrates is different. I can do this, but I will call it a night for today.

**Comment by primaeval** [comment]
Ok. I'm looking for the bbcid bug.

**Comment by primaeval** [comment]
Actually seeing as all the bitrates except live HQ are 128 you could just make it default to the highest bitrate, which should be 128 and even default to Akamai to make it simple.

**Pull request merged**
