### PR TITLE
radio favourites format fix

### PR DESCRIPTION
**Pull request by primaeval**
This works for me. The searches might be too fragile if they start tweaking the css format rules.

### CODE REVIEW

**Comment by CaptainTK** [comment]
Thank you very much!

**Comment by CaptainTK** [comment]
On the regrexps in general: I suspect that at some point of time we will have to switch to JSON anyways. I would just like to see that it becomes somewhat semi-official.

**Comment by primaeval** [comment]
Is there a secret json feed somewhere? I thought it was just some of the bbcid functions that used it.

**Comment by CaptainTK** [comment]
Apparantly, there is json for everything. I can't recall where I found it, but somebody already wrote a scraper for that.

**Comment by primaeval** [comment]
They would be handy if it isn't locked away with api keys.

**Comment by CaptainTK** [comment]
IIRC IBL does not need any API keys. It still seemed somewhat sketchy to me.

**Comment by primaeval** [comment]
Have you got a link?

**Comment by CaptainTK** [comment]
Can you see this comment?

http://ibl.api.bbci.co.uk/ibl/v1/home/highlights?lang=en&rights=tv&availability=available
gets you the Highlights. It would be easy to parse them, it's all JSON.

I can't seem to find an official spec or a license for it, though.

**Pull request merged**
