### PR TITLE
image fix

### PR DESCRIPTION
**Pull request by primaeval**

### CODE REVIEW

**Comment by CaptainTK** [comment]
I was expecting this to happen. Thanks for the fix.

As you know, it will take some weeks before I can submit a new version to the official repo. Off on holidays.

**Comment by primaeval** [comment]
Let me know how to do it and I'll submit it to the official repo.  It's not really fair to let all the users go without, especially over Christmas. No humbug here. ;)

**Comment by CaptainTK** [comment]
I usually follow [these instructions](http://kodi.wiki/view/HOW-TO:Create_add-on_PRs_using_Git_Subtree_Merging). However, I am not sure they will accept your submission since everything has come from me so far. You are one of the authors mentioned in addon.xml, so it is certainly worth a try. I can comment on the PR, if it helps. I just don't have a dev environment with me.

Before you go down that road the following files will need updates:

1. addon.xml: new versions, supposedly 2.5.3
1. changelog.txt: Description of the changes
1. there should be a new release in this repo (I can do that from here).

If you are serious, please provide a PR with items 1+2, please call the commit simply "[version 2.5.2]". I can then take care of 3, and afterwards you should be able to create a PR to the official repo. Make sure it is merged to the helix branch.

**Comment by primaeval** [comment]
Let's have a go. A few of them know me already.

**Comment by CaptainTK** [comment]
Off you go. :-)

**Comment by primaeval** [comment]
That wasn't too bad. I can see why you don't want to do it too often though. ;)
Could you add a message and check it for me.
https://github.com/xbmc/repo-plugins/pull/814

**Comment by CaptainTK** [comment]
Seems like it wasn't necessary. Well done!

The main issue is keeping the fork of repo-plugins in sync. This gives me a headache every time.

**Comment by primaeval** [comment]
Thanks. It might be easier just to delete the fork and fork it again.
These are the commands I use. They might work as a bash script.
```
git clone https://github.com/primaeval/repo-plugins.git
cd repo-plugins/
git remote add myaddon https://github.com/primaeval/plugin.video.iplayerwww.git
git fetch myaddon
git checkout -b myaddon_branch myaddon/master
git checkout helix
git rm -r plugin.video.iplayerwww/
git read-tree --prefix=plugin.video.iplayerwww/ -u myaddon_branch
git diff --staged
git commit -m "[plugin.video.iplayerwww] 2.5.3"
git push origin helix
```

**Comment by CaptainTK** [comment]
It is quite a big repo to clone it again every time, so I try to avoid deleting it whenever possible.

**Comment by primaeval** [comment]
I'm probably a bit spoiled here. ;)
http://beta.speedtest.net/result/5904803370

**Pull request merged**
